artifacts_root: artifacts_root


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url : Dataset\winequalitydata.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion
  